### ISSUE TITLE
Why does it start a new shell?

### ISSUE THREAD

**Issue by oobles** [kranners/ktx#1]
When I select an environment without the dash option it creates a new shell so I lose the previous prompt configuration.

Before:  <machine>:<directory> <user>$

After: bash-3.2$

I'd like to keep my prompt configuration.

**Comment by kranners** [comment]
Problem is that scripts aren't scoped to your current shell.
A quick fix would be to just comment the line that opens up the new shell, and execute it with `source ./ktx.sh` instead.
